version: '3'

services:
  jenkins:
    image: 161192472568.dkr.ecr.us-east-1.amazonaws.com/jenkins-controller:latest
    container_name: jenkins
    restart: always
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
